<a href="https://colab.research.google.com/github/markcatinoy/Numerical_Method/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
import numpy as np
print(f'NumPy library version: {np.__version__}')

NumPy library version: 1.19.5


In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6,]])
print(b)

[[1 2 3]
 [4 5 6]]
(3,)


In [10]:

b[0,0] = 7
print(b)

[[7 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[1,2,3],[4,5,6,],[7,8,9,]])
print(c)

In [12]:
d = np.full((2,2),7)
print(d)

[[7 7]
 [7 7]]


In [15]:
e = np.eye(2,)
print(e)

[[1. 0.]
 [0. 1.]]


In [19]:
f = np.diagonal([[1,2,3],[4,5,6,],[7,8,9,]])
print(f)

[1 5 9]


In [21]:
g = np.empty((0,10))
print(g)

[]


In [22]:
i = np.zeros((2,2))
print(i)

[[0. 0.]
 [0. 0.]]


In [27]:
print(e)
print(i)
print(e+i)
print(e-i)
print(i-e)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
