<a href="https://colab.research.google.com/github/markcatinoy/Numerical_Method/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

In [2]:
#Chio's Method
import numpy as np


In [11]:
A = np.array([ [1,2,3],[2,3,3],[3,4,-2] ])
print(A)
print(round(np.linalg.det(A)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5
