<a href="https://colab.research.google.com/github/markcatinoy/Numerical_Method/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Determinants of Matrix using numpy.linalg.det

In [15]:
import numpy as np
A = np.array ([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13.999999999999996
-14
