<a href="https://colab.research.google.com/github/markcatinoy/Numerical_Method/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operation

Create a NumPy program that performs the operations of the given matrices:

1. sum = A +B
2. difference1 = B - A
3. difference2 = A - B


In [12]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])

In [16]:
 #Sum of A and B
 print(A + B)

[[ 1 -3]
 [ 6  4]]


In [15]:
#Difference of B and A
print(B - A)

[[11 -3]
 [-2  2]]


In [4]:
#Difference of A and B
print(A - B)

[[-11   3]
 [  2  -2]]
